image: node:8.11.1

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli@7.2.0
    - npm install
    - ng build --prod --baseHref=/moowda/frontend
    - mv dist/moowda-frontend/* public/
  artifacts:
    paths:
      - public
  only:
    - master
